# Generated by Django 6.1.1 on 2026-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('boda', 'Boda'), ('social', 'Social'), ('corporativo', 'Corporativo'), ('cumpleanos', 'Cumpleaños'), ('otro', 'Otro')], max_length=20)),
                ('cliente_contacto', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('plazo_limite', models.DateField()),
            ],
        ),
    ]
